name: Check and Create Tag.

on:
  push:
    branches:
      - terraform

jobs:
  check_and_create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: set global user variables
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: see git tag
      run: |
        git tag | wc -l

    - name: Check and Create Tag
      run: |
        # Get the number of tags in the repository
        tag_count=$(git tag | wc -l)

        # Check if there are no tags
        if [ $tag_count -eq 0 ]; then
            git tag -a 0.0.0 -m "Initial version 0.0.0"
            echo "Created a new tag: 0.0.0"
            git push origin 0.0.0
        else
            echo "Tags already exist. No action needed."
        fi
      continue-on-error: true  

    - name: see tag
      run: git describe --tags --abbrev=0
