name: "Bump release version"

on: [push]
 
permissions: read-all

jobs:
  version-bump:
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4 
      - name: Get project version
        run: |
          CURRENT_PROJECT_VERSION=$(npm pkg get version | tr -d '"')
          echo "CURRENT_PROJECT_VERSION=${CURRENT_PROJECT_VERSION}" >> "$GITHUB_ENV"
          echo "CURRENT_PROJECT_VERSION=${CURRENT_PROJECT_VERSION}"
          
      - name: see last commit message
        run: git log -1 --pretty=%B    

      - name: Check version impact and increment accordingly
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if ! echo "${COMMIT_MSG}" | grep -qE '\[\b[A-Z][A-Z0-9_]+-[1-9][0-9]*\]\[(major|minor|patch)\]:\s\w+' &> /dev/null ; then
            echo "Squashed commit message does not meet the standard regex"
            exit 1
          fi
          COMMIT_IMPACT_TYPE=$(echo "${COMMIT_MSG}" | grep -oE "(major|minor|patch)" | head -1)
          case $COMMIT_IMPACT_TYPE in
            major)
              NEXT_PROJECT_VERSION=$(echo "${CURRENT_PROJECT_VERSION}" | awk -F. '/[0-9]+\./{$1++;$2=0;$3=0;print}' OFS=.)
              echo "NEXT_PROJECT_VERSION=${NEXT_PROJECT_VERSION}" >> "$GITHUB_ENV"
              ;;
            minor)
              NEXT_PROJECT_VERSION=$(echo "${CURRENT_PROJECT_VERSION}" | awk -F. '/[0-9]+\./{$2++;$3=0;print}' OFS=.)
              echo "NEXT_PROJECT_VERSION=${NEXT_PROJECT_VERSION}" >> "$GITHUB_ENV"
              ;;
            patch)
              NEXT_PROJECT_VERSION=$(echo "${CURRENT_PROJECT_VERSION}" | awk -F. '/[0-9]+\./{$3++;print}' OFS=.)
              echo "NEXT_PROJECT_VERSION=${NEXT_PROJECT_VERSION}" >> "$GITHUB_ENV"
              ;;
            *)
              echo "Invalid impact type"
              exit 1;;
          esac
      - name: Set project version
        run: |
          npm version --no-git-tag-version "$NEXT_PROJECT_VERSION"
          echo "NEXT_PROJECT_VERSION=$NEXT_PROJECT_VERSION"
          
      - name: Commit, tag and push
        run: |
          git add --update
          git config --global user.name "ACN-rakshith"
          git config --global user.email "rakshith.kashyap@accenture.com"
          git commit -m "Bumping Version from ${CURRENT_PROJECT_VERSION} to ${NEXT_PROJECT_VERSION}"
          git tag -a "${NEXT_PROJECT_VERSION}" -m "Release v${NEXT_PROJECT_VERSION}"
          git push --atomic --follow-tags origin init-javascript "${NEXT_PROJECT_VERSION}"   
