name: Get Latest Tag

on:
  push:
    branches:
      - terraform

jobs:
  get_latest_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: fetch tags
      run: git fetch -t

    - name: Get Latest Tag
      id: get_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "Latest Tag: $latest_tag"
      shell: bash

    - name: Use the Latest Tag
      run: echo "The latest tag is ${{ steps.get_tag.outputs.latest_tag }}"
