name: Terraform Format

on:
  push: 
    paths-ignore:
      - 'docs/**' # Adjust the path to exclude any directories from formatting

jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Format
        run: terraform fmt -recursive
