name: Terraform Format..

on: [push]
    

jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.9" # Replace with the desired Terraform version

      - name: Terraform Format
        run: terraform fmt -recursive
